Sitegeist:
  Iconoclasm:
    mediaTypes:
      'image/jpeg':
        enabled: true
        command: 'jpegoptim --quiet --strip-all --force --stdout {input} > {output}'
      'image/png':
        enabled: true
        command: 'pngquant --strip --force --output {output} -- {input}'
