Neos:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: '%env:SMTP_HOST%'
        port: '%env(int):SMTP_PORT%'
        encryption: 'tls'
        username: '%env:SMTP_USERNAME%'
        password: '%env:SMTP_PASSWORD%'
