#                                                                        #
# Routes configuration                                                   #

##
# Ttree OutOfBandRendering sub routes
-
  name: 'Ttree.OutOfBandRendering'
  uriPattern: '<TtreeOutOfBandRenderingSubRoutes>'
  subRoutes:
    'TtreeOutOfBandRenderingSubRoutes':
      package: 'Ttree.OutOfBandRendering'
      variables:
        'defaultUriSuffix': ''
